name: batcollect
channels:
  - defaults
dependencies:
  - python==3.10.*

  # Basics
  - requests

  # Etc
  - pip
  - pip:
    - mat73  # For NREL synthetic data
    - tqdm
    - selenium
    - jupyterlab
    - battery-data-toolkit>=0.3
